---
- name: Envia correo
  mail:
    host: "{{ servidor_correo }}" 
    port: "{{ puerto }}"
    username: "{{ correo_gmail }}"
    password: "{{ password_gmail }}"
    to: "{{ destinatario }}"
    subject: "{{ asunto }}"
    body: "{{ mensaje }}"
    subtype: html
    charset: utf8
#    attach: "{{ adjuntos if adjuntos is defined else '' }}"
...
